server:
  address: 127.0.0.1
  port: 8091

components:
  default-data:
    secret-key: 'AYASDI_ICUHDHDSEK_SKIMS'

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod
